NSGA-II:
  pop_size: 10

DDPG:
  critic_hidden_size: 25
  soft_update_tau: 0.005
  critic_value_discount: 0.999
  critic_lr: 0.001
  actor_lr: 0.0005

MHA:
  hidden_size: 125

ReplayBuffer:
  buffer_size: 10000

Shared:
  roster_size: 8