Meta:
  num_gens: 3

NSGAII:
  popsize: 16
  noise_std: 0.3
  noise_mean: 0
  num_teams_formed_each_MHA: 15

DDPG:
  critic_hidden_size: 25
  soft_update_tau: 0.005
  critic_value_discount: 0.999
  critic_lr: 0.001
  actor_lr: 0.0005

MHA:
  hidden_size: 125

ReplayBuffer:
  buffer_size: 10000

Shared:
  roster_size: 6
  team_size: 3