Meta:
  num_gens: 600

NSGAII:
  pop_size: 24
  policy_mutation_noise_std: 0.2
  policy_mutation_noise_mean: 0
  num_teams_formed_each_MHA: 3

DDPG:
  critic_hidden_size: 25
  soft_update_tau: 0.005
  critic_value_discount: 0.999
  critic_lr: 0.001
  actor_lr: 0.0005
  num_rollouts: 72
  batch_size: 1440
  num_grad_steps: 72

MHA:
  hidden_size: 128

ReplayBuffer:
  buffer_size: 28800

Shared:
  roster_size: 3