Meta:
  num_objs: 1

Environment:
  dimensions: [10, 10]
  ep_length: 15  # episode length
  timestep_penalty: 0
  global_reward_mode: "Aggregated"  # Options: "Aggregated", "Final"
  local_reward_mode: "exponential" # Options: inverse_distance
  local_reward_kneecap: 100.0 # Distance from POI at which local reward is exactly 1 (higher if closer)
  pois:
    - obj: 1
      location: [5, 8]
      radius: 3
      coupling: 1
      obs_window: [0, 90]
      reward: 4
      repeat: True

Agents:
  starting_locs: [[1, 1]]
  num_sensors: [4]
  observation_radii: [15]
  max_step_sizes: [1]
