Meta:
  num_objs: 2
  
Environment:
  dimensions: [100, 100]
  ep_length: 5 # episode length
  timestep_penalty: 0
  pois:
    - obj: 1
      location: [20, 25]
      radius: 5
      coupling: 1
      obs_window: [0, 100]
      reward: 9
      repeat: False
    - obj: 2
      location: [50, 55]
      radius: 3
      coupling: 2
      obs_window: [0, 90]
      reward: 4
      repeat: True

Agents:
  starting_locs: [[50, 50], [50, 50], [50, 50]]
  num_sensors: [4, 4, 4]
  observation_radii: [10, 10, 10]
  max_step_sizes: [3, 3, 3]