Meta:
  num_objs: 2
  
Environment:
  dimensions: [100, 100]
  timestep_penalty: 0
  pois:
    - obj: 1
      location: [20, 25]
      radius: 5
      coupling: 1
      obs_window: [0, 100]
      reward: 9
      repeat: False
    - obj: 2
      location: [50, 55]
      radius: 3
      coupling: 2
      obs_window: [0, 90]
      reward: 4
      repeat: True