Meta:
  num_objs: 1

Environment:
  dimensions: [10, 10]
  ep_length: 15  # episode length
  timestep_penalty: 0
  global_reward_mode: "Aggregated"  # Options: "Aggregated", "Final"
  local_reward_mode: "exponential" # Options: inverse_distance, exponential
  local_reward_kneecap: 10.0 # Distance from POI at which local reward is exactly 1 (higher if closer)
  local_reward_temp: 5 # higher, the smoother the reward gradient (irrelevant if reward mode is inverse_distnace)

  # Objectives must start from 0.
  pois:
    - obj: 0
      location: [5, 8]
      radius: 3
      coupling: 1
      obs_window: [0, 90]
      reward: 4
      repeat: True

Agents:
  starting_locs: [[3, 3]] #Remember, the dimensionality of this influences the state input size. Length determines team size!!!
  num_sensors: [4] # Remember, these many sensors for detecting pois + these many sensors for detecting other agents
  observation_radii: [2]
  max_step_sizes: [1]